### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 554001833** [victorchall/EveryDream2trainer#201] opened 2023-06-21 10:30 UTC
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by victorchall** [comment] 2023-06-21 16:50
Try install Cuda 11.8:

https://developer.nvidia.com/cuda-11-8-0-download-archive

If you are on linux and trying to install this manually yourself its possible you'll need to set LD_LIBRARY_PATH as well.


Find the cuda library location:
`find / -name libcudart.so* 2>/dev/null`

result:
`/home/freon/EveryDream2trainer/venv/lib/python3.10/site-packages/nvidia/cuda_runtime/lib/libcudart.so.11.0
/home/freon/ml-ed2/venv/lib/python3.10/site-packages/nvidia/cuda_runtime/lib/libcudart.so.11.0`

Set path hint for bitsandbytes (should work with either example above)
`export LD_LIBRARY_PATH=/home/freon/EveryDream2trainer/venv/lib/python3.10/site-packages/nvidia/cuda_runtime/lib`

**Comment by victorchall** [comment] 2023-06-21 17:40
I've updated documents with this as well.

**Comment by victorchall** [comment] 2023-06-25 16:16
This is a dupe of https://github.com/victorchall/EveryDream2trainer/issues/200, closing

**Closed by victorchall** 2023-06-25 16:16 UTC
